//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapProxy.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.apache.org/axis2", ConfigurationName="ServiceReference1.QueryServicePortType")]
    public interface QueryServicePortType {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetDetail", ReplyAction="urn:GetDetailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoapProxy.ServiceReference1.GetDetailResponse GetDetail(SoapProxy.ServiceReference1.GetDetailRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetList", ReplyAction="urn:GetListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoapProxy.ServiceReference1.GetListResponse GetList(SoapProxy.ServiceReference1.GetListRequest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetClinic", ReplyAction="urn:GetClinicResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoapProxy.ServiceReference1.GetClinicResponse GetClinic(SoapProxy.ServiceReference1.GetClinicRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetail", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class GetDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string recordtype;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string pid;
        
        public GetDetailRequest() {
        }
        
        public GetDetailRequest(string recordtype, string pid) {
            this.recordtype = recordtype;
            this.pid = pid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetailResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class GetDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public GetDetailResponse() {
        }
        
        public GetDetailResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetList", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string certificate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string number;
        
        public GetListRequest() {
        }
        
        public GetListRequest(string certificate, string number) {
            this.certificate = certificate;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetListResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public GetListResponse() {
        }
        
        public GetListResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClinic", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class GetClinicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string certificate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string qtype;
        
        public GetClinicRequest() {
        }
        
        public GetClinicRequest(string certificate, string number, string qtype) {
            this.certificate = certificate;
            this.number = number;
            this.qtype = qtype;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetClinicResponse", WrapperNamespace="http://ws.apache.org/axis2", IsWrapped=true)]
    public partial class GetClinicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.apache.org/axis2", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string @return;
        
        public GetClinicResponse() {
        }
        
        public GetClinicResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryServicePortTypeChannel : SoapProxy.ServiceReference1.QueryServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryServicePortTypeClient : System.ServiceModel.ClientBase<SoapProxy.ServiceReference1.QueryServicePortType>, SoapProxy.ServiceReference1.QueryServicePortType {
        
        public QueryServicePortTypeClient() {
        }
        
        public QueryServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapProxy.ServiceReference1.GetDetailResponse SoapProxy.ServiceReference1.QueryServicePortType.GetDetail(SoapProxy.ServiceReference1.GetDetailRequest request) {
            return base.Channel.GetDetail(request);
        }
        
        public string GetDetail(string recordtype, string pid) {
            SoapProxy.ServiceReference1.GetDetailRequest inValue = new SoapProxy.ServiceReference1.GetDetailRequest();
            inValue.recordtype = recordtype;
            inValue.pid = pid;
            SoapProxy.ServiceReference1.GetDetailResponse retVal = ((SoapProxy.ServiceReference1.QueryServicePortType)(this)).GetDetail(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapProxy.ServiceReference1.GetListResponse SoapProxy.ServiceReference1.QueryServicePortType.GetList(SoapProxy.ServiceReference1.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public string GetList(string certificate, string number) {
            SoapProxy.ServiceReference1.GetListRequest inValue = new SoapProxy.ServiceReference1.GetListRequest();
            inValue.certificate = certificate;
            inValue.number = number;
            SoapProxy.ServiceReference1.GetListResponse retVal = ((SoapProxy.ServiceReference1.QueryServicePortType)(this)).GetList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapProxy.ServiceReference1.GetClinicResponse SoapProxy.ServiceReference1.QueryServicePortType.GetClinic(SoapProxy.ServiceReference1.GetClinicRequest request) {
            return base.Channel.GetClinic(request);
        }
        
        public string GetClinic(string certificate, string number, string qtype) {
            SoapProxy.ServiceReference1.GetClinicRequest inValue = new SoapProxy.ServiceReference1.GetClinicRequest();
            inValue.certificate = certificate;
            inValue.number = number;
            inValue.qtype = qtype;
            SoapProxy.ServiceReference1.GetClinicResponse retVal = ((SoapProxy.ServiceReference1.QueryServicePortType)(this)).GetClinic(inValue);
            return retVal.@return;
        }
    }
}
